### ISSUE TITLE
Native driver or doctrine abstraction

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-mongodb-adapter#1]
Question extracted from prooph/proophessor#20: 

Do we make a pure mongodb adapter or a doctrine-mongodb adapter? I really like the abstraction doctrine-mongodb provides!

**Comment by codeliner** [comment]
That's a good question. I thought about the same thing after @jsor provided the [event-store-doctrine-adapter](https://github.com/prooph/event-store-doctrine-adapter).  In the end it does the same as the zf2 db adapter but using doctrine instead. A third version would be a plain PDO adapter without any third party library involved which would be the fastest adapter to connect to a RDBMS.
A good reason for the doctrine adapter was (and is) that the event store and the read model typically share the same database (when using a RDBMS only), so if you use doctrine also for your read model you can share the connection between ES and read model. Same if you favour to use ZF2 DB adapter then your choice would be the event-store-zf2-adapter.

I think that is true for doctrine-mongodb too. So +1 for the doctrine-mongodb adapter. If someone needs more performance and wants to use the native driver only then he can write his own performance optimized adapter. We should keep it simple and support the most common use case.

**Comment by prolic** [comment]
About connection reuse: You can also share the same db connection between doctrine and zend-db. Only thing you have to do is push the pdo connection to the service manager and fetch it from the connection factory there. Could be that you'll need custom connection factories to achieve this.

**Comment by codeliner** [comment]
yeah, with ZF2 everything is possible somehow :-). But the event-store can be integrated in any framework. I think outside of ZF2 the doctrine-adapter is the preferred one.

**Comment by codeliner** [comment]
#4 uses native driver and it works fine so I think we can close the issue.
