### ISSUE TITLE
How to handle transactions

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-mongodb-adapter#2]
Question extracted from prooph/proophessor#20: 

MongoDB does not support transactions, but it has atomic modifiers and ttl documents, so enough tools to build transactions manually. For the event stream a transactional behavior would be useful, right?
I think of something like this:

```
- Start transaction sets a property into the adapter that transaction is running
- During in-transaction persistence we add a "inTransaction":true property on the document.
- All findById and findAll and similar queries check for the inTransaction property
- After transaction is finished, we can remove the inTransaction property with an atomic modifier to enable the new state
- An entry marked "inTransation" has a ttl (time-to-life) on the server side, in case the process dies, we don't want to have pending transactions in the database, so they get cleaned up after some time.
```

If we do something like this, which TTL will we use? MySQL InnoDB has a innodb_lock_wait_timeout of 50 secs by default f.e.

**Comment by codeliner** [comment]
Unfortunately, I have no production experience with mongoDB. Used it for a private project only. My clients always use Oracle. Don't ask me why :-)
Do we have other (simpler) options? Or maybe we should first have a look on how the event stream(s) can be organized with mongoDB. Let us discuss this in #3 first.

**Comment by prolic** [comment]
I can do that, if you want to ;)

**Comment by codeliner** [comment]
Transaction support would be great. I'm also fine with the way you want to implement it. It sounds good and works without magic so go for it :+1:

**Comment by codeliner** [comment]
#4 ships with transaction support.
