### ISSUE TITLE
Bad transaction support

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-mongodb-adapter#26]
MongoDB does not support atomic operations across collections, only for a single document.
Therefore we need to make the following changes:
- use the $isolated operator for marking a transaction as done
- put every aggregate in a separate collection
- mark in the readme, that this adapter does not work properly in a sharded cluster.
- provide some notes on how to update an existing database

**Comment by prolic** [comment]
for reference: http://docs.mongodb.org/manual/core/write-operations-atomicity/

**Comment by codeliner** [comment]
A note: We can let the user decide how aggregates should be stored depending on the [stream strategy](https://github.com/prooph/event-store/blob/master/docs/repositories.md#stream-strategies)
We should make sure that the second point (put every aggregate in a separate collection)
is working correctly when the AggregateStream strategy is used and suggest this strategy as the best one in combination with the mongo db adapter.
