### ISSUE TITLE
use a strategy for collection name and index

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store-mongodb-adapter#48]
It would be nice to have a naming strategy, like `Zend\Hydrator` has, to determine the collection name (`MongoDb\MongoDbEventStoreAdapter::getCollectionName()`) and an index strategy (`MongoDbEventStoreAdapter::createIndexes()`).

This is useful if you want to have one collection per aggregate id and it's more flexible.

@prolic What do you think?

**Comment by prolic** [comment]
the stream name comes from the event store. this is already configurable.

**Comment by sandrokeil** [comment]
Yes but an suffix `_stream` is added and the uuid hyphen is replaced by an underscore. We want to avoid this.

**Comment by prolic** [comment]
You have the streamCollectionMap for this. The doctrine adapter behaves the same.

**Comment by sandrokeil** [comment]
In my case the stream name is an uuid (aggregate_id) and therefore I can not use the streamCollectionMap. Additional indexes are needed if I want to read the event store directly.

**Comment by prolic** [comment]
if I understand you correctly, you don't like this:

```
$streamname = $aggregateType . '-' . $aggregateId;
```

and you want this instead:

```
$streamname = $aggregateId;
```

right?

**Comment by prolic** [comment]
if so, you need to override the method `protected function determineStreamName($aggregateId)` in your aggregate repository and write there this:

```
return new StreamName($aggregateId);
```

**Comment by sandrokeil** [comment]
That's already done. Let me explain the use case.

I have an root aggregate with uuid 123-123 (User) and this a collection in MongoDB. All changes (events) are stored in this collection only for that aggregate. If i create a new root aggregate 444-444 (User) a new collection will be created and so on. This works so far, but I need some extensions to optimize it and it could be useful for others too. I don't want to change the default behaviour, but make it configurable.

I have no collections like a user table, I have collections like rows of a user table. I hope this helps to understand my concern.

**Comment by prolic** [comment]
`but I need some extensions to optimize it` don't know what you mean, sorry.
@codeliner perhaps you can assist?

**Comment by prolic** [comment]
We'll do this!

**Comment by Ocramius** [comment]
Note: as discussed in the chat today, this affects the DBAL event-store as well.

**Comment by prolic** [comment]
Question: Should we use strategy classes or just a callback?

**Comment by sandrokeil** [comment]
I think we have only one method per Interface (`__invoke()`). I would prefer to define Interfaces, but also accept callables. Is this the same for the doctrine adapter?

**Comment by prolic** [comment]
Yes
Am 08.03.2016 12:12 schrieb "Sandro Keil" notifications@github.com:

**Comment by prolic** [comment]
This repo is only for Event Store v6 series, with v7 things changed a lot, so this will not be done anymore.
