### ISSUE TITLE
use native MongoDB data types whenever possible

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store-mongodb-adapter#53]
We don't use the native [`UTCDatetime` (MongoDB ext)](http://php.net/manual/de/class.mongodb-bson-utcdatetime.php) data type for the [`created_at` field](https://github.com/prooph/event-store-mongodb-adapter/blob/master/src/MongoDbEventStoreAdapter.php#L191). We also [cast all metadata to string](https://github.com/prooph/event-store-mongodb-adapter/blob/master/src/MongoDbEventStoreAdapter.php#L195).

I guess native data types are more useful, especially if advanced stuff is done with the event store and maybe increases the performance. It's useful for the index strategy (#48) too.

We should consider this for the next major version with the `mongodb` extension. The same applies for the other event store adapters.

**Comment by prolic** [comment]
Problem is mysql f.e. does not store microseconds in datetime field

**Comment by sandrokeil** [comment]
Maybe Oracle MySQL has no support, but [MariaDB has](https://mariadb.com/kb/en/mariadb/timestamp/). Most Distros have changed to MariaDB or? However, we should use it where it's possible.

**Comment by prolic** [comment]
This repo is only for Event Store v6 series, with v7 things changed a lot, so this will not be done anymore.
