### ISSUE TITLE
The backend should treat all Dates as UTC

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-mongodb-adapter#6]
Extracted from #4. Based on a comment by @prolic 
The frontend is required to set the appropriate timezone.
Currently we use "$dateTime = new DateTime()", which relies on php's internal timezone setting. If you query the data from another server with different timezone settings, you get wrong DateTimes for the created_at property of an event.

**Comment by prolic** [comment]
How would you like to implement this?
We can do it on every single adapter (calculate the offset from UTC and substract) or direct in the DomainMessage class?

**Comment by codeliner** [comment]
We should fix that in the DomainMessage class and publish a bugfix release.
