### ISSUE TITLE
Feature: Store events in different event collections based on the stream_name

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-mongodb-adapter#7]
@prolic One feature I can think of would be to store events in different collections based on the stream_name to not have all events in one big event collection. Would multiple event collections have advantages over one big collection when dealing with huge amount of events?

**Comment by prolic** [comment]
No not at all. You can use the auto sharding feature of mongo db to shard
the events across servers. That said, it would not even make sense to shard
by stream name, you can shard per event id. If you got enouh servers, you
can end up with one event per server (all versions of it ).

How nice is that? ;-)
Am 09.08.2015 13:21 schrieb "Alexander Miertsch" notifications@github.com:

**Comment by codeliner** [comment]
very nice :+1: . Ok then we don't need to add complexity to the adapter and can close the issue
