### ISSUE TITLE
remove [wip] from project description on github

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-mongodb-adapter#9]

**Comment by codeliner** [comment]
done :)

Btw as soon as all adapters are updated to support prooph/event-store 5.x I will release new versions of the adapters too. What version should the mongo db adapter get: `0.2` or `1.0`? I prefer `1.0`. It looks good and the public API of the adapter will be stable.

**Comment by prolic** [comment]
when 5.0 is final, let's release 1.0 soon after.

**Comment by prolic** [comment]
well, doesn't make sense, what i said, but... :)
